// ============================================
// DATA ANGGOTA IRMANUFA - KABINET GOLDEN GENERATION 2027-2029
// TOTAL: 94 ANGGOTA (59 AKTIF + 35 PASIF)
// ============================================

const IRMANUFA_DATA = {
  members: [
    // ========================================
    // BADAN PENGAWAS HARIAN (6 AKTIF)
    // KODE: 26.01.001 - 26.01.006
    // ========================================
    {
      code: "26.01.001",
      name: "Agung Ubaidillah",
      gender: "L",
      position: "Ketua Umum",
      division: "Badan Pengawas Harian",
      status: "active",
    },
    {
      code: "26.01.002",
      name: "Nalendra Maheswara",
      gender: "L",
      position: "Wakil Ketua Umum",
      division: "Badan Pengawas Harian",
      status: "active",
    },
    {
      code: "26.01.003",
      name: "Tasya Amelia Putri",
      gender: "P",
      position: "Sekretaris I",
      division: "Badan Pengawas Harian",
      status: "active",
    },
    {
      code: "26.01.004",
      name: "Lidya Febrianti",
      gender: "P",
      position: "Sekretaris II",
      division: "Badan Pengawas Harian",
      status: "active",
    },
    {
      code: "26.01.005",
      name: "Nursiva Salsabila",
      gender: "P",
      position: "Bendahara I",
      division: "Badan Pengawas Harian",
      status: "active",
    },
    {
      code: "26.01.006",
      name: "Fahri Maulana",
      gender: "L",
      position: "Bendahara II",
      division: "Badan Pengawas Harian",
      status: "active",
    },

    // ========================================
    // DIVISI KEAGAMAAN DAN KEMASJIDAN (9 AKTIF)
    // KODE: 26.02.001 - 26.02.009
    // ========================================
    {
      code: "26.02.001",
      name: "Moldi Trio Ringgo Hervavi",
      gender: "L",
      position: "Ketua Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.002",
      name: "Tsany Lukmanul Hakim",
      gender: "L",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.003",
      name: "Ilyas Sahbi",
      gender: "L",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.004",
      name: "Galank",
      gender: "L",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.005",
      name: "Putri Dwi Rahayu",
      gender: "P",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.006",
      name: "Iim Indiyani",
      gender: "P",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.007",
      name: "Sarah",
      gender: "P",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.008",
      name: "Muhamad Abdul Fatah Cahya Putrawan",
      gender: "L",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },
    {
      code: "26.02.009",
      name: "Pricillia Berliana Putri",
      gender: "P",
      position: "Anggota Divisi Keagamaan dan Kemasjidan",
      division: "Divisi Keagamaan dan Kemasjidan",
      status: "active",
    },

    // ========================================
    // DIVISI HUBUNGAN MASYARAKAT (9 AKTIF)
    // KODE: 26.03.001 - 26.03.009
    // ========================================
    {
      code: "26.03.001",
      name: "Muhammad Fahri",
      gender: "L",
      position: "Ketua Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.002",
      name: "Yoga Ady Lesmana",
      gender: "L",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.003",
      name: "M Yasin",
      gender: "L",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.004",
      name: "Abdullah Fardani",
      gender: "L",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.005",
      name: "Bhita Andini",
      gender: "P",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.006",
      name: "Aliend Nur Zahra",
      gender: "P",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.007",
      name: "Wiji Astuti",
      gender: "P",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.008",
      name: "Rizkia Meliani Safitri",
      gender: "P",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },
    {
      code: "26.03.009",
      name: "Faiz Rahardika Chandra",
      gender: "L",
      position: "Anggota Divisi Hubungan Masyarakat",
      division: "Divisi Hubungan Masyarakat",
      status: "active",
    },

    // ========================================
    // DIVISI PERINGATAN HARI BESAR ISLAM (8 AKTIF)
    // KODE: 26.04.001 - 26.04.008
    // ========================================
    {
      code: "26.04.001",
      name: "Akhmad Fauzi Hanafi",
      gender: "L",
      position: "Ketua Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },
    {
      code: "26.04.002",
      name: "Rizky Pratama",
      gender: "L",
      position: "Anggota Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },
    {
      code: "26.04.003",
      name: "Baats Jauhari",
      gender: "L",
      position: "Anggota Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },
    {
      code: "26.04.004",
      name: "Reza Firman Maulana",
      gender: "L",
      position: "Anggota Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },
    {
      code: "26.04.005",
      name: "Wafiq Azizah",
      gender: "P",
      position: "Anggota Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },
    {
      code: "26.04.006",
      name: "Siska Komalasari",
      gender: "P",
      position: "Anggota Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },
    {
      code: "26.04.007",
      name: "Arya Agung Fadilah",
      gender: "L",
      position: "Anggota Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },
    {
      code: "26.04.008",
      name: "Tasya Putriyanto",
      gender: "P",
      position: "Anggota Divisi Peringatan Hari Besar Islam",
      division: "Divisi Peringatan Hari Besar Islam",
      status: "active",
    },

    // ========================================
    // DIVISI PENGEMBANGAN SUMBER DAYA MANUSIA (9 AKTIF)
    // KODE: 26.05.001 - 26.05.009
    // ========================================
    {
      code: "26.05.001",
      name: "Dwi Fathi Malika Lubna",
      gender: "P",
      position: "Ketua Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.002",
      name: "Zahwa Andiyah Putri",
      gender: "P",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.003",
      name: "Anisa Ramadhani",
      gender: "P",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.004",
      name: "Aisyah Fitriani",
      gender: "P",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.005",
      name: "Danis Fahrudin",
      gender: "L",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.006",
      name: "Habib Maulana Azizi",
      gender: "L",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.007",
      name: "Faturrochman",
      gender: "L",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.008",
      name: "Agung Saputra",
      gender: "L",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },
    {
      code: "26.05.009",
      name: "Aisyah Zaskia",
      gender: "P",
      position: "Anggota Divisi Pengembangan Sumber Daya Manusia",
      division: "Divisi Pengembangan Sumber Daya Manusia",
      status: "active",
    },

    // ========================================
    // DIVISI KESEKRETARIATAN (9 AKTIF)
    // KODE: 26.06.001 - 26.06.009
    // ========================================
    {
      code: "26.06.001",
      name: "Chindy Kharisya Putri",
      gender: "P",
      position: "Ketua Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.002",
      name: "Siti Aisyah",
      gender: "P",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.003",
      name: "Ranti Puspita Sari",
      gender: "P",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.004",
      name: "Kareena",
      gender: "P",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.005",
      name: "Faqih Guntur Samudra",
      gender: "L",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.006",
      name: "Rayhan Satriawan",
      gender: "L",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.007",
      name: "Ikhwan Nurfadilah",
      gender: "L",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.008",
      name: "Aditya Saputra",
      gender: "L",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },
    {
      code: "26.06.009",
      name: "Dewi Anggraeni",
      gender: "P",
      position: "Anggota Divisi Kesekretariatan",
      division: "Divisi Kesekretariatan",
      status: "active",
    },

    // ========================================
    // DIVISI PUBLIKASI DEKORASI DAN DOKUMENTASI (8 AKTIF)
    // KODE: 26.07.001 - 26.07.008
    // ========================================
    {
      code: "26.07.001",
      name: "Daffina Hardiyanti Putri",
      gender: "P",
      position: "Ketua Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },
    {
      code: "26.07.002",
      name: "Caskia Dwi Pratiwi",
      gender: "P",
      position: "Anggota Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },
    {
      code: "26.07.003",
      name: "Hafizzah",
      gender: "P",
      position: "Anggota Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },
    {
      code: "26.07.004",
      name: "Laila Mukarromah",
      gender: "P",
      position: "Anggota Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },
    {
      code: "26.07.005",
      name: "Hikaru Rian Putra",
      gender: "L",
      position: "Anggota Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },
    {
      code: "26.07.006",
      name: "Rizky Akbar",
      gender: "L",
      position: "Anggota Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },
    {
      code: "26.07.007",
      name: "Fazril Januar",
      gender: "L",
      position: "Anggota Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },
    {
      code: "26.07.008",
      name: "Rizky Arya Widani",
      gender: "L",
      position: "Anggota Divisi Publikasi Dekorasi dan Dokumentasi",
      division: "Divisi Publikasi Dekorasi dan Dokumentasi",
      status: "active",
    },

    // ========================================
    // ANGGOTA PASIF (35 ORANG)
    // KODE: 26.08.001 - 26.08.035
    // ========================================
    {
      code: "26.08.001",
      name: "Dedi Juwanto",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.002",
      name: "Salwa Revtiani",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.003",
      name: "Tuti Apriyani",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.004",
      name: "Indana Zulfa",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.005",
      name: "Sariati Nurfadilah",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.006",
      name: "Rafa Reita",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.007",
      name: "Maryatul Qibtiyah",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.008",
      name: "Rayhan Nadi Agung Wijaya",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.009",
      name: "Dinar Hamzah Azzayat",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.010",
      name: "Sarinih",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.011",
      name: "Linda Permata",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.012",
      name: "Fathan Abid Hafizh",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.013",
      name: "Muhammad Rizky",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.014",
      name: "Mawar",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.015",
      name: "Nazwa Aulia Rahmania Ruhli Syahputri",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.016",
      name: "Izza Jazirah",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.017",
      name: "Gally Cahya Putrawan",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.018",
      name: "M Soni Arsadi",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.019",
      name: "Devita Agustin",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.020",
      name: "M Syuja Aqil",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.021",
      name: "Putri Nabila",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.022",
      name: "Farid Alita",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.023",
      name: "Gadis Apriyani",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.024",
      name: "Putri Nirmala",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.025",
      name: "M Arif Hidayat",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.026",
      name: "Yovanda Alfa Reza",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.027",
      name: "Siti Hajizah",
      gender: "P",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.028",
      name: "Abdurachman Iskandar",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.029",
      name: "Angga Brhamntyo",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.030",
      name: "Rifqi Maulana",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.031",
      name: "Rizky Hardiansyah",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.032",
      name: "Adi Wibowo",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.033",
      name: "Rafiq Wahid Alifudin",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.034",
      name: "Sukran Alramadhana",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
    {
      code: "26.08.035",
      name: "Abdullah Fardani",
      gender: "L",
      position: "Anggota Pasif",
      division: "Anggota Pasif",
      status: "passive",
    },
  ],
};
